# Configuración Nixpacks para Railway
# Fuerza incluir todas las carpetas del proyecto

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node server.js"
